In [191]:
import pandas as pd

In [192]:
stats = pd.read_csv("player_mvp_stats.csv")

In [193]:
stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [194]:
stats.columns

Index(['Unnamed: 0', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG',
       'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT',
       'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'Year', 'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS'],
      dtype='object')

In [195]:
del stats["Unnamed: 0"]

In [196]:
pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          50
3P            0
3PA           0
3P%        2042
2P            0
2PA           0
2P%          84
eFG%         50
FT            0
FTA           0
FT%         462
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [197]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]].head()

             Player  3PA
2    Elden Campbell  0.0
3     Irving Thomas  0.0
18       Jack Haley  0.0
20      Keith Owens  0.0
30  Benoit Benjamin  0.0

In [198]:
stats[pd.isnull(stats["FG%"])][["Player", "FGA"]].head()

               Player  FGA
103   Adrian Caldwell  0.0
250        Guy Rucker  0.0
428        Gani Lawal  0.0
1961     Ronny Turiaf  0.0
2240      Lari Ketner  0.0

In [199]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]].head()

              Player  FTA
77        John Coker  0.0
92      Jason Sasser  0.0
103  Adrian Caldwell  0.0
119     Bruno Šundov  0.0
158   Jamal Robinson  0.0

In [200]:
stats = stats.fillna(0)

In [201]:
predictors = ["Age", "G", "GS", "MP", "FG", "FGA", 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS']

In [202]:
train = stats[~(stats["Year"] == 2021)]
test = stats[stats["Year"] == 2021]

In [203]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.5)

In [204]:
reg.fit(train[predictors],train["Share"])

Ridge(alpha=0.5)

In [205]:
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [206]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [207]:
combination.head()

               Player  Share  predictions
630      Aaron Gordon    0.0     0.014808
631     Austin Rivers    0.0    -0.013289
632           Bol Bol    0.0     0.003258
633  Facundo Campazzo    0.0    -0.003356
634  Greg Whittington    0.0     0.012802

In [208]:
combination.sort_values("predictions", ascending=False).head(20)

                        Player  Share  predictions
9907     Giannis Antetokounmpo  0.345     0.206612
8624               Joel Embiid  0.580     0.163508
641               Nikola Jokić  0.961     0.155044
10997              Luka Dončić  0.042     0.150842
3736              LeBron James  0.001     0.148004
3651             Stephen Curry  0.449     0.143449
4177              Kevin Durant  0.000     0.141621
4174              James Harden  0.001     0.140298
11784          Zion Williamson  0.000     0.129730
3876         Russell Westbrook  0.005     0.120089
6093              Jimmy Butler  0.000     0.118648
7464            Damian Lillard  0.038     0.117347
5328             Kawhi Leonard  0.001     0.114507
3863              Bradley Beal  0.000     0.103949
12493             De'Aaron Fox  0.000     0.102648
4178              Kyrie Irving  0.000     0.102232
11308               Trae Young  0.000     0.100934
3728             Anthony Davis  0.000     0.098294
11358              Rudy Gobert  0.008     0.095486
2592   Shai Gilgeous-Alexander  0.000     0.094311

In [209]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.0026721369873755575

In [210]:
df = combination
actual = df.sort_values("Share", ascending=False)
predicted = df.sort_values("predictions", ascending=False)
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [211]:
predicted.merge(actual, on="Player").head(20)

,Player,Share_x,predictions_x,Predicted_Rk,Share_y,predictions_y,Rk
0,Giannis Antetokounmpo,0.345,0.206612,1,0.345,0.206612,4
1,Joel Embiid,0.580,0.163508,2,0.580,0.163508,2
2,Nikola Jokić,0.961,0.155044,3,0.961,0.155044,1
3,Luka Dončić,0.042,0.150842,4,0.042,0.150842,6
4,LeBron James,0.001,0.148004,5,0.001,0.148004,15
5,Stephen Curry,0.449,0.143449,6,0.449,0.143449,3
6,Kevin Durant,0.000,0.141621,7,0.000,0.141621,531
7,James Harden,0.001,0.140298,8,0.001,0.140298,13
8,Zion Williamson,0.000,0.129730,9,0.000,0.129730,251
9,Russell Westbrook,0.005,0.120089,10,0.005,0.120089,11
10,Jimmy Butler,0.000,0.118648,11,0.000,0.118648,442
11,Damian Lillard,0.038,0.117347,12,0.038,0.117347,7
12,Kawhi Leonard,0.001,0.114507,13,0.001,0.114507,14
13,Bradley Beal,0.000,0.103949,14,0.000,0.103949,488
14,De'Aaron Fox,0.000,0.102648,15,0.000,0.102648,246
15,Kyrie Irving,0.000,0.102232,16,0.000,0.102232,530
16,Trae Young,0.000,0.100934,17,0.000,0.100934,235
17,Anthony Davis,0.000,0.098294,18,0.000,0.098294,504
18,Rudy Gobert,0.008,0.095486,19,0.008,0.095486,10
19,Shai Gilgeous-Alexander,0.000,0.094311,20,0.000,0.094311,310

In [212]:
actual.head(5)

                     Player  Share  predictions  Rk
641            Nikola Jokić  0.961     0.155044   1
8624            Joel Embiid  0.580     0.163508   2
3651          Stephen Curry  0.449     0.143449   3
9907  Giannis Antetokounmpo  0.345     0.206612   4
1389             Chris Paul  0.138     0.073963   5

In [213]:
predicted

                      Player  Share  predictions  Predicted_Rk
9907   Giannis Antetokounmpo  0.345     0.206612             1
8624             Joel Embiid  0.580     0.163508             2
641             Nikola Jokić  0.961     0.155044             3
10997            Luka Dončić  0.042     0.150842             4
3736            LeBron James  0.001     0.148004             5
...                      ...    ...          ...           ...
9437           Patrick McCaw  0.000    -0.048016           536
13476          Killian Hayes  0.000    -0.049499           537
9915             P.J. Tucker  0.000    -0.054636           538
3862        Anžejs Pasečņiks  0.000    -0.059305           539
11768           Didi Louzada  0.000    -0.068682           540

[540 rows x 4 columns]

In [214]:
def find_mean_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    aps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            aps.append(found / seen)
        seen += 1

    return sum(aps) / len(aps)

In [215]:
mean_ap = find_mean_ap(combination)

In [216]:
mean_ap

0.7636363636363636

In [217]:
years = list(range(1991,2022))

In [218]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_mean_ap(combination))

In [219]:
aps

[0.47000000000000003,
 0.3922012578616352,
 0.8166666666666667,
 0.3871428571428571,
 0.8392857142857142,
 0.9266666666666665,
 0.6831536388140161,
 0.9666666666666666,
 0.692063492063492,
 0.563498817966903,
 0.42630718954248364,
 0.6434782608695653,
 0.7683333333333333,
 0.9428571428571428,
 0.8142857142857143,
 0.7392857142857142,
 0.4386904761904762,
 0.6976190476190476,
 0.6334586466165414,
 0.9266666666666665,
 0.8333333333333333,
 0.8111111111111111,
 0.7909090909090909,
 0.6375757575757576,
 0.9428571428571428,
 0.7636363636363636]

In [220]:
sum(aps) / len(aps)

0.7133750296086192

In [221]:
all_predictions[-1].sort_values("Share", ascending=False).head(5)

                     Player  Share  predictions
641            Nikola Jokić  0.961     0.155044
8624            Joel Embiid  0.580     0.163508
3651          Stephen Curry  0.449     0.143449
9907  Giannis Antetokounmpo  0.345     0.206612
1389             Chris Paul  0.138     0.073963

In [222]:
all_predictions[-1].sort_values("predictions", ascending=False).head(5)

                      Player  Share  predictions
9907   Giannis Antetokounmpo  0.345     0.206612
8624             Joel Embiid  0.580     0.163508
641             Nikola Jokić  0.961     0.155044
10997            Luka Dončić  0.042     0.150842
3736            LeBron James  0.001     0.148004

In [223]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        all_predictions.append(combination)
        aps.append(find_mean_ap(combination))
    return sum(aps) / len(aps), aps, all_predictions

In [224]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[25:], predictors)

In [225]:
mean_ap

0.7965704665704666

In [249]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[25:], predictors)

In [250]:
mean_ap

0.7550198412698412

In [251]:
aps

[0.8625,
 0.5449999999999999,
 0.6311111111111112,
 0.7698412698412698,
 1.0,
 0.7216666666666667]

In [252]:
all_predictions[1].sort_values("Share", ascending=False).head(20)

                      Player  Share  predictions
6352       Russell Westbrook  0.879     0.304151
11011           James Harden  0.746     0.424231
12407          Kawhi Leonard  0.495     0.336973
6705            LeBron James  0.330     0.243183
2536           Isaiah Thomas  0.080     0.171216
5577           Stephen Curry  0.051     0.622014
14076  Giannis Antetokounmpo  0.007     0.012833
11317              John Wall  0.007     0.102588
4101           Anthony Davis  0.002     0.110570
5571            Kevin Durant  0.002     0.496357
12338          DeMar DeRozan  0.001     0.182928
8429             R.J. Hunter  0.000     0.000000
8587          Garrett Temple  0.000     0.000000
8586         Darren Collison  0.000     0.000000
7140           Trevor Booker  0.000     0.000000
8585             Buddy Hield  0.000     0.000000
8584            Ben McLemore  0.000     0.000000
8583           Arron Afflalo  0.000     0.000000
8582        Anthony Tolliver  0.000     0.000000
8431             Robin Lopez  0.000     0.000000

In [253]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    return predictions

In [254]:
add_ranks(all_predictions[1])

                  Player  Share  predictions  Predicted_Rk   Rk
6352   Russell Westbrook  0.879     0.304151             5    1
11011       James Harden  0.746     0.424231             3    2
12407      Kawhi Leonard  0.495     0.336973             4    3
6705        LeBron James  0.330     0.243183             6    4
2536       Isaiah Thomas  0.080     0.171216             8    5
...                  ...    ...          ...           ...  ...
13873      José Calderón  0.000     0.000000           164  482
13874      Kent Bazemore  0.000     0.000000           163  483
13875     Kris Humphries  0.000     0.000000           162  484
13876    Lamar Patterson  0.000     0.000000           161  485
14091         Tony Snell  0.000     0.000000           486  486

[486 rows x 5 columns]

In [255]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[25:], predictors)

In [256]:
aps

[0.8333333333333333,
 0.8111111111111111,
 0.7909090909090909,
 0.6375757575757576,
 0.9428571428571428,
 0.7636363636363636]

In [258]:
add_ranks(all_predictions[1])

                  Player  Share  predictions  Predicted_Rk   Rk
6352   Russell Westbrook  0.879     0.186822             1    1
11011       James Harden  0.746     0.174678             2    2
12407      Kawhi Leonard  0.495     0.131398             8    3
6705        LeBron James  0.330     0.174309             3    4
2536       Isaiah Thomas  0.080     0.124295             9    5
...                  ...    ...          ...           ...  ...
11019       Trevor Ariza  0.000     0.008945           164  482
5874      Reggie Jackson  0.000     0.008983           163  483
11319      Marcin Gortat  0.000     0.008999           162  484
11009        Eric Gordon  0.000     0.009215           161  485
780           Mike Tobey  0.000    -0.053241           486  486

[486 rows x 5 columns]

In [296]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_mean_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [277]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[25:], predictors)

In [ ]:
mean_ap

In [281]:
all_predictions["diff"] = (all_predictions["Rk"] - all_predictions["Predicted_Rk"])

In [286]:
all_predictions[all_predictions["Rk"] < 5].sort_values("diff").head(10)

                  Player  Share  predictions  Predicted_Rk  Rk  diff
6253       Kawhi Leonard  0.484     0.107728            10   2    -8
2931      Damian Lillard  0.205     0.103705            11   4    -7
11696       Nikola Jokić  0.210     0.117183            10   4    -6
1361         Paul George  0.352     0.118573             9   3    -6
12407      Kawhi Leonard  0.495     0.131398             8   3    -5
3651       Stephen Curry  0.449     0.143449             6   3    -3
6340   Russell Westbrook  0.371     0.129505             6   4    -2
641         Nikola Jokić  0.961     0.155044             3   1    -2
3720        LeBron James  0.746     0.161786             4   2    -2
867         James Harden  0.955     0.184002             2   1    -1

In [289]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes

In [292]:
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [ ]:
mean_ap, aps, all_predictions = backtest(stats, rf, years[25:], predictors + ["NPos", "NTm"])

In [ ]:
mean_ap